<?php

class modWebSocietyUsersPasswordForgotProcessor extends modObjectUpdateProcessor{

    public $classKey = "modUser";

    public function initialize(){

        if(!$username = trim($this->getProperty("username"))){
            return "Не был указан логин или емейл";
        }

        $this->properties = array();

        $q = $this->modx->newQuery($this->classKey);

        $alias = $q->getAlias();

        $q->innerJoin("modUserProfile", "Profile");
        $q->where(array(
            "username"  => $username,
            "OR:Profile.email:="  => $username,
        ));

        $q->select(array(
            "{$alias}.id",
        ));

        $q->limit(1);

        if($id = (int)$this->modx->getValue($q->prepare())){
            $this->setProperty("id", $id);
        }
        else{
            return "Пользователь не был найден";
        }

        return parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function beforeSet(){
        $object = & $this->object;

        $min = $this->modx->getOption("password_generated_length", 6);

        if(!$password = $object->generatePassword($min)){
            return "Не удалось сгенерировать пароль";
        }

        $this->setProperties(array(
            "active"    => 1,
            "password" => $password,
        ));

        return parent::beforeSet();
    }


    public function beforeSave(){
        $object = & $this->object;

//
//
//        print_r($object->toArray());
//
//        return "Debug";
        return parent::beforeSave(); // TODO: Change the autogenerated stub
    }


    public function afterSave(){
        /*
         * Высылаем новый пароль
         * */

        if(empty($this->modx->smarty)){
            $this->modx->invokeEvent("OnHandleRequest");
        }

        $this->modx->smarty->assign("username", $this->object->username);
        $this->modx->smarty->assign("password", $this->getProperty("password"));

        if($msg = $this->modx->smarty->fetch("messages/users/password_reminder.tpl")){
            $this->object->sendEmail($msg, array(
                "subject"   => "Новый пароль на сайте {$this->modx->config['site_name']}",
            ));
        }

        return parent::afterSave(); // TODO: Change the autogenerated stub
    }

    public function success($msg = "", $object = array()){
        return parent::success("Пароль выслан Вам на почту");
    }
}

return 'modWebSocietyUsersPasswordForgotProcessor';
